### ISSUE TITLE
Undefined method 'unpack' error

### ISSUE THREAD

**Issue by Li-Kezhi** [ne0dim/spa2csv#1]
Thank you for sharing your code!

While using your code, I encountered an error:

> E:/Downloads/spa2csv-master/spa2csv-master/spa2csv-0.1.rb:48:in `<main>': undefined method `unpack' for nil:NilClass (NoMethodError)

Since I have no experience using Ruby, I totally have no idea what leads to this problem. Could you please help? Thank you!

**Comment by ne0dim** [comment]
Thank you for your support. As far as I know the problem might be with the version of ruby you're using to run the code.
Could you write your ruby version and platform?

The problem with this error could also be caused by incorrect SPA file. It would be great if you could post your file here, so that I could find the difference with my spectra files.

**Comment by Li-Kezhi** [comment]
My Ruby version:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32]
And my Windows version:
Windows 10 (1511)
Thank you!

**Comment by Li-Kezhi** [comment]
[series00120000.zip](https://github.com/ne0dim/spa2csv/files/260948/series00120000.zip)

**Comment by ne0dim** [comment]
Hi again. I tried to convert your file both on my Windows and Linux installations with various ruby versions and every time it was successful.
Are you providing the program with correct spectrum file (spa type) as an argument? 
I could reproduce this only by giving the text file argument. When using your "series00120000.spa" file it converts correctly.

**Comment by ne0dim** [comment]
Here is your converted file.
[series00120000_converted.zip](https://github.com/ne0dim/spa2csv/files/264854/series00120000_converted.zip)

**Comment by Li-Kezhi** [comment]
Thank you again! The code worked on my computer today, though I changed nothing... Maybe a restart is necessary when first installing Ruby? Anyway, it did work! Thank you so much!
